---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Copy custom index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
  notify: restart nginx
  become: yes

- name: Ensure NGINX is running
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

