---
- name: Maven Installation
  hosts: allservers
  become: yes
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: full

    - name: Install Maven
      ansible.builtin.apt:
        name: maven
        state: present

